apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: muxcore-data
  labels:
    app.kubernetes.io/name: muxcore
    app.kubernetes.io/component: core
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
