---
- name: Deploy environment config file
  ansible.builtin.template:
    src: muxcore.conf.j2
    dest: "{{ muxcore_config_dir }}/muxcore.conf"
    owner: root
    group: root
    mode: "0640"
  notify: restart muxcore

- name: Deploy muxcore.json config
  when: muxcore_config_json | length > 0
  ansible.builtin.template:
    src: muxcore.json.j2
    dest: "{{ muxcore_config_dir }}/muxcore.json"
    owner: root
    group: "{{ muxcore_system_group }}"
    mode: "0640"
  notify: restart muxcore

- name: Deploy systemd unit file
  ansible.builtin.template:
    src: muxcored.service.j2
    dest: /etc/systemd/system/muxcored.service
    owner: root
    group: root
    mode: "0644"
  notify: restart muxcore

- name: Deploy logrotate configuration
  when: muxcore_logrotate_enable
  ansible.builtin.template:
    src: logrotate.j2
    dest: /etc/logrotate.d/muxcore
    owner: root
    group: root
    mode: "0644"
