# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from muxcore.module.v1 import registration_pb2 as muxcore_dot_module_dot_v1_dot_registration__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    # Softened for SDK packaging across grpcio minors; regenerate stubs when upgrading tools.
    warnings.warn(
        f'grpcio {GRPC_VERSION} < generated {GRPC_GENERATED_VERSION}; '
        'upgrade grpcio or regenerate stubs if RPCs fail.',
        RuntimeWarning,
        stacklevel=2,
    )


class ModuleRegistrationStub:
    """ModuleRegistration is the service that sidecar module binaries call
    to register themselves with the core at startup and unregister at shutdown.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/muxcore.module.v1.ModuleRegistration/Register',
                request_serializer=muxcore_dot_module_dot_v1_dot_registration__pb2.RegisterRequest.SerializeToString,
                response_deserializer=muxcore_dot_module_dot_v1_dot_registration__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.Unregister = channel.unary_unary(
                '/muxcore.module.v1.ModuleRegistration/Unregister',
                request_serializer=muxcore_dot_module_dot_v1_dot_registration__pb2.UnregisterRequest.SerializeToString,
                response_deserializer=muxcore_dot_module_dot_v1_dot_registration__pb2.UnregisterResponse.FromString,
                _registered_method=True)
        self.BootstrapRegister = channel.unary_unary(
                '/muxcore.module.v1.ModuleRegistration/BootstrapRegister',
                request_serializer=muxcore_dot_module_dot_v1_dot_registration__pb2.BootstrapRegisterRequest.SerializeToString,
                response_deserializer=muxcore_dot_module_dot_v1_dot_registration__pb2.BootstrapRegisterResponse.FromString,
                _registered_method=True)


class ModuleRegistrationServicer:
    """ModuleRegistration is the service that sidecar module binaries call
    to register themselves with the core at startup and unregister at shutdown.
    """

    def Register(self, request, context):
        """Register is called by a sidecar module binary to register itself with core.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Unregister(self, request, context):
        """Unregister is called by a sidecar module binary at shutdown.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BootstrapRegister(self, request, context):
        """BootstrapRegister is called by external modules (not spawned by core)
        to obtain a signed client certificate using a one-time bootstrap token.
        The module presents its token and a CSR; core validates the token and
        returns a signed certificate. The module then reconnects with mTLS.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModuleRegistrationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=muxcore_dot_module_dot_v1_dot_registration__pb2.RegisterRequest.FromString,
                    response_serializer=muxcore_dot_module_dot_v1_dot_registration__pb2.RegisterResponse.SerializeToString,
            ),
            'Unregister': grpc.unary_unary_rpc_method_handler(
                    servicer.Unregister,
                    request_deserializer=muxcore_dot_module_dot_v1_dot_registration__pb2.UnregisterRequest.FromString,
                    response_serializer=muxcore_dot_module_dot_v1_dot_registration__pb2.UnregisterResponse.SerializeToString,
            ),
            'BootstrapRegister': grpc.unary_unary_rpc_method_handler(
                    servicer.BootstrapRegister,
                    request_deserializer=muxcore_dot_module_dot_v1_dot_registration__pb2.BootstrapRegisterRequest.FromString,
                    response_serializer=muxcore_dot_module_dot_v1_dot_registration__pb2.BootstrapRegisterResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'muxcore.module.v1.ModuleRegistration', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('muxcore.module.v1.ModuleRegistration', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ModuleRegistration:
    """ModuleRegistration is the service that sidecar module binaries call
    to register themselves with the core at startup and unregister at shutdown.
    """

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/muxcore.module.v1.ModuleRegistration/Register',
            muxcore_dot_module_dot_v1_dot_registration__pb2.RegisterRequest.SerializeToString,
            muxcore_dot_module_dot_v1_dot_registration__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Unregister(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/muxcore.module.v1.ModuleRegistration/Unregister',
            muxcore_dot_module_dot_v1_dot_registration__pb2.UnregisterRequest.SerializeToString,
            muxcore_dot_module_dot_v1_dot_registration__pb2.UnregisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BootstrapRegister(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/muxcore.module.v1.ModuleRegistration/BootstrapRegister',
            muxcore_dot_module_dot_v1_dot_registration__pb2.BootstrapRegisterRequest.SerializeToString,
            muxcore_dot_module_dot_v1_dot_registration__pb2.BootstrapRegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
