# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: muxcore/module/v1/registration.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'muxcore/module/v1/registration.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$muxcore/module/v1/registration.proto\x12\x11muxcore.module.v1\"<\n\x18\x42ootstrapRegisterRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12\x11\n\tmodule_id\x18\x02 \x01(\t\"s\n\x19\x42ootstrapRegisterResponse\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\x12\x13\n\x0bsigned_cert\x18\x03 \x01(\t\x12\x0f\n\x07key_pem\x18\x04 \x01(\t\x12\x0f\n\x07\x63\x61_cert\x18\x05 \x01(\t\"\x85\x01\n\x0fRegisterRequest\x12\x11\n\tmodule_id\x18\x01 \x01(\t\x12\x11\n\tmesh_addr\x18\x03 \x01(\t\x12\x18\n\x10min_core_version\x18\x04 \x01(\t\x12\x32\n\x0bmodule_info\x18\x05 \x01(\x0b\x32\x1d.muxcore.module.v1.ModuleInfo\"\xc2\x01\n\nModuleInfo\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\t\x12\r\n\x05roles\x18\x04 \x03(\t\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x06 \x01(\t\x12\x14\n\x0c\x63\x61pabilities\x18\x07 \x03(\t\x12\x12\n\ndepends_on\x18\x08 \x03(\t\x12\x18\n\x10min_core_version\x18\t \x01(\t\x12\x11\n\thttp_addr\x18\n \x01(\t\"W\n\x10RegisterResponse\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\x12\x11\n\tmesh_addr\x18\x03 \x01(\t\x12\x0f\n\x07node_id\x18\x04 \x01(\t\"&\n\x11UnregisterRequest\x12\x11\n\tmodule_id\x18\x01 \x01(\t\"*\n\x12UnregisterResponse\x12\x14\n\x0c\x61\x63knowledged\x18\x01 \x01(\x08\x32\xb4\x02\n\x12ModuleRegistration\x12S\n\x08Register\x12\".muxcore.module.v1.RegisterRequest\x1a#.muxcore.module.v1.RegisterResponse\x12Y\n\nUnregister\x12$.muxcore.module.v1.UnregisterRequest\x1a%.muxcore.module.v1.UnregisterResponse\x12n\n\x11\x42ootstrapRegister\x12+.muxcore.module.v1.BootstrapRegisterRequest\x1a,.muxcore.module.v1.BootstrapRegisterResponseBDZBgithub.com/Muxcore-Media/core/proto/gen/muxcore/module/v1;modulev1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'muxcore.module.v1.registration_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZBgithub.com/Muxcore-Media/core/proto/gen/muxcore/module/v1;modulev1'
  _globals['_BOOTSTRAPREGISTERREQUEST']._serialized_start=59
  _globals['_BOOTSTRAPREGISTERREQUEST']._serialized_end=119
  _globals['_BOOTSTRAPREGISTERRESPONSE']._serialized_start=121
  _globals['_BOOTSTRAPREGISTERRESPONSE']._serialized_end=236
  _globals['_REGISTERREQUEST']._serialized_start=239
  _globals['_REGISTERREQUEST']._serialized_end=372
  _globals['_MODULEINFO']._serialized_start=375
  _globals['_MODULEINFO']._serialized_end=569
  _globals['_REGISTERRESPONSE']._serialized_start=571
  _globals['_REGISTERRESPONSE']._serialized_end=658
  _globals['_UNREGISTERREQUEST']._serialized_start=660
  _globals['_UNREGISTERREQUEST']._serialized_end=698
  _globals['_UNREGISTERRESPONSE']._serialized_start=700
  _globals['_UNREGISTERRESPONSE']._serialized_end=742
  _globals['_MODULEREGISTRATION']._serialized_start=745
  _globals['_MODULEREGISTRATION']._serialized_end=1053
# @@protoc_insertion_point(module_scope)
