{{- if or .Values.secrets.tls.enabled .Values.secrets.joinToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "muxcore.fullname" . }}-secrets
  labels:
    {{- include "muxcore.labels" . | nindent 4 }}
type: Opaque
data:
  {{- with .Values.secrets.tls }}
  {{- if .enabled }}
  tls.crt: {{ .cert | b64enc }}
  tls.key: {{ .key | b64enc }}
  {{- end }}
  {{- end }}
  {{- with .Values.secrets.joinToken }}
  join-token: {{ . | b64enc }}
  {{- end }}
{{- end }}
